# Copier/adapter selon votre environnement MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/medilink?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
app.demo.patientId=4


GEMINI_API_KEY=AIzaSyBV7YvXy2jnc1lE6L_wOMqmWAuhqDHrxOY
gemini.api.key=AIzaSyBV7YvXy2jnc1lE6L_wOMqmWAuhqDHrxOY