# Copier/adapter selon votre environnement MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/medilink?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
